CREATE DATABASE animedata;

USE animedata;


CREATE TABLE `animedata`.`atitles` (
  `aid` INT NULL,
  `japtitle` TEXT CHARACTER SET 'utf8mb4' NULL,
  `entitle` TEXT CHARACTER SET 'utf8mb4' NULL)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4904,'アチ&シパカ','Aachi and Ssipak');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4904,'アチ&シパカ','Aachi & Ssipak');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7058,'バツ&テリー','Bats and Terry');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3446,'アカギ','Akagi');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (28,'アキラ','Akira');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (314,'カイト','A Kite');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2640,'バース','Birth: A War of Two Worlds');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2320,'ベック','Beck - Mongolian Chop Squad');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3447,'ボイン','Boin');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3447,'ボイン','Boin Lecture');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2704,'のぞみ ウィッチィズ','Bewitching Nozomi');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1050,'ブラム!','Blame!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (914,'バイオ·ハンター','BioHunter');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6782,'あきそら','Autumn Sky');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7400,'あそいく','Asobi ni Ikuyo: Bombshells from the Sky');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2214,'どたから','Animal Treasure Island');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11910,'ばなにゃ','Bananya');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4861,'ぼくらの','Bokurano');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8556,'アナザー','Another');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11820,'カナメヲ','A Linchpin');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8337,'ハトアリ','Alice in Heartland');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8337,'ハトアリ','Alice in the Country of Hearts');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2369,'ブリーチ','Bleach');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8292,'ベントー','Ben-To');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5901,'ペンもん','A Penguin`s Troubles');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7443,'モーパイ','Bodacious Space Pirates');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (12322,'あおおに ~じ・あにめぇしょん~','Aooni the Blue Monster: The Animation');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11837,'レッチュ ゲッチュ サルゲッチュ','Ape Escape: Let Me Get You');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6182,'アキカン!','Akikan!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9348,'アイカツ! アイドルカツドウ!','Aikatsu! Idol Activities!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11253,'ばくおん!!','Bakuon!!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7251,'バクマン.','Bakuman');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10432,'ブレイド&ソウル','Blade and Soul');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10432,'ブレイド&ソウル','Blade & Soul');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11321,'あんハピ♪','Anne-Happy');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11081,'だんちがい','Big Difference');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10111,'ばらかもん','Barakamon');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7934,'べるぜバブ','Beelzebub');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9358,'アムネシア','Amnesia');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4196,'エア・ギア','Air Gear');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2779,'カメレオン','Bite Me! Chameleon');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11819,'クロムクロ','Black Relic');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2759,'バロムワン','Barom One');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11851,'ベルセルク','Berserk (2016)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8292,'ベン・トー','Ben-To');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6046,'こんにちは アン','Before Green Gables');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6564,'エンジェル ビーツ!','Angel Beats!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1353,'エイトマン アフター','8 Man After');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5611,'バットマン ゴッサムナイト','Batman');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5611,'バットマン ゴッサムナイト','Batman: Gotham Knight');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10114,'ベヨネッタ ブラッディフェイト','Bayonetta: Bloody Fate');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11683,'あまんちゅ!','Amanchu!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4897,'バッカーノ!','Baccano!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3078,'あずきちゃん','Azuki');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9391,'ちゅうずもう','A Sumo Wrestler`s Tale');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (627,'はだしのゲン','Barefoot Gen');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10385,'アオハライド','Blue Spring Ride');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (634,'エアマスター','AirMaster');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (634,'エアマスター','Air Master');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2,'サザンアイズ','3x3 Eyes');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2,'サザンアイズ','3x3 Eyes - Immortals');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4681,'バーテンダー','Bartender TV');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (644,'ブルーシード','Blue Seed');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4338,'サルゲッチュ ~オンエアー~','Ape Escape');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9631,NULL,'007 Boy and the Galaxy Raider');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9632,NULL,'007 Boy and the Underground Empire');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4637,NULL,'009-1');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8699,NULL,'009 Re:Cyborg');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6239,NULL,'07 Ghost');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6239,NULL,'07-Ghost');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5996,NULL,'1000% for That Girl');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1001,NULL,'100 Stories');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2170,NULL,'10 Chikan Association');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2854,NULL,'10 Tokyo Warriors');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2867,NULL,'10 Tokyo Warriors (2001)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2854,NULL,'10 Warriors of Tokyo');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6751,NULL,'11 Eyes');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5726,NULL,'12 Female Teachers');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (26,NULL,'12K');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (26,NULL,'12 Kingdoms');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9629,NULL,'15 Children Space Adventure');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3370,NULL,'19th-Century Boy Takamaru');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4401,NULL,'1st squad');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5671,NULL,'20faces');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4943,NULL,'21 Emon: To Space! The Barefoot Princess');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5323,NULL,'21 Emon: Welcome to the Space!!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2003,NULL,'23 year old Female Teacher');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7195,NULL,'2nd Lieutenant Norakuro: Sunday Magic');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1423,NULL,'2x1');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1769,NULL,'2 X 2 = The Legend of Shinobu');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2213,NULL,'\"30');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1383,NULL,'3000 Leagues in Search of Mother');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1391,NULL,'3D Magical Play');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9592,NULL,'3 Iron Musketeers');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3,NULL,'3x3 Eyes: Legend of the Divine Demon');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7243,NULL,'4-1/2 Tatami Mythological Chronicles');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7243,NULL,'4.5 Tatami Mythological Chronicles');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4568,NULL,'5 Centimeters per Second');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4568,NULL,'5 cm per second');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4568,NULL,'5cm per Second');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4568,NULL,'5cm/s');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7248,NULL,'5leaves');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9109,NULL,'663114');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (12684,NULL,'6HP Six Hearts Princess Pink or Black');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9593,NULL,'77 Group`s Secret');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (853,NULL,'7o7');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (853,NULL,'7 of Seven');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (198,NULL,'801 T.T.S. Airbats');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2706,NULL,'80 Days Around the World With Willy Fog');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (217,NULL,'8th Team');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (12014,NULL,'91 Days');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3354,NULL,'9 Love Stories');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (299,NULL,'9 O`clock Woman');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3683,NULL,'A 1001 Nights');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2837,NULL,'ab');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6888,NULL,'Abandoned Cat Little Tora');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (70,NULL,'Abenobashi Magical Shopping District');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (118,NULL,'ABJ');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7431,NULL,'Abnormal Physiology Seminar');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8287,NULL,'Abnormal Physiology Seminar (TV)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10888,NULL,'A Boring World Where the Concept of Dirty Jokes Doesn`t Exist');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8166,NULL,'A Bridge to the Starry Skies');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7027,NULL,'Absent Minded Penelope');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7035,NULL,'Absent Minded Penelope (2009)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2837,NULL,'Absolute Boy');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10745,NULL,'Absolute Duo');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2840,NULL,'Absolute Justice Love Pheromone');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4486,NULL,'Absolutely Invincible Raijin-Oh');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5674,NULL,'Absolutely Lovely Children');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9346,NULL,'Absolute Whiteness: Magical Girl');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2435,NULL,'AC');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (12136,NULL,'ACCA: 13-Territory Inspection Dept.');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4920,NULL,'Accelerando ~Whisper of Descending Angels~');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8691,NULL,'Accel World');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11598,NULL,'Ace Attorney');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9881,NULL,'Ace of Diamond');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10739,NULL,'Ace of Diamond (2014)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11115,NULL,'Ace of Diamond: Second Season');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9881,NULL,'Ace of the Diamond');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5975,NULL,'A Certain Magical Index');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7599,NULL,'A Certain Magical Index 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7599,NULL,'A Certain Magical Index II');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8694,NULL,'A Certain Magical Index: The Miracle of Endymion');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8694,NULL,'A Certain Magical Index the Movie: The Miracle of Endymion');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6460,NULL,'A Certain Scientific Railgun');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7975,NULL,'A Certain Scientific Railgun OVA');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9484,NULL,'A Certain Scientific Railgun S');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10453,NULL,'A Certain Scientific Railgun S OVA');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8107,NULL,'A-Channel');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (75,NULL,'A cheeky angel');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8056,NULL,'A Child`s Metaphysics');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5029,NULL,'A Child`s Time');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1424,NULL,'A Chinese Ghost Story');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1424,NULL,'A Chinese Ghost Story: The Tsui Hark Animation');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6982,NULL,'A Christmas Carol');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5609,NULL,'A Connectiv System');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11104,NULL,'A Corpse Is Buried Under Sakurako`s Feet');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7020,NULL,'Action Series Puppets: New Three Musketeers');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11690,NULL,'Active Raid: Special Public Security Fifth Division Third Mobile Assault Eighth Unit');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11831,NULL,'Active Raid: Special Public Security Fifth Division Third Mobile Assault Eighth Unit - Second');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11048,NULL,'\"Actually');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8229,NULL,'A Dark Rabbit has Seven Lives');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5379,NULL,'A day of Chameko');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11476,NULL,'Addict Gangbang -No Escape! Sayaka x 1428 Students-');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8120,NULL,'A Deer of Nine Colors');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1235,NULL,'Adeus Legend OVA II');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (765,NULL,'Adieu 999');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (765,NULL,'Adieu Galaxy Express 999');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4339,NULL,'A Direction of the Day After Tomorrow');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1650,NULL,'A Dog of Flanders');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1651,NULL,'A Dog of Flanders: My Friend Patrasche');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1651,NULL,'A Dog of Flanders: My Patrasche');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11304,NULL,'A Donkey Got a Bit Sulky');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (441,NULL,'A.D. Police Files');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (441,NULL,'AD.Police - The Mad Criminal Investigation File');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9201,NULL,'A Drifting Life');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2367,NULL,'Adrift in the Pacific');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1397,NULL,'Advancer Tina');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9541,NULL,'Advancing Giants');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3604,NULL,'Adventure Boy Shadar');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1130,NULL,'Adventure Duo');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1130,NULL,'Adventure Kid');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2391,NULL,'Adventure King Beet');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3703,NULL,'Adventure King Beet Exelion');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9594,NULL,'Adventure of Haedol');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1517,NULL,'Adventures of Goku');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2325,NULL,'Adventures of Kotetsu');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3665,NULL,'Adventures of Little El Cid');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1351,NULL,'Adventures of Maya the Honeybee');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (477,NULL,'Adventures of Patapata Aircraft');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3085,NULL,'Adventures of Pepero the Andes Boy');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2294,NULL,'Adventures of Peter Pan');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3641,NULL,'Adventures of Pinocchio');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2211,NULL,'Adventures of Puss-in-Boots');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5747,NULL,'Adventures of the Little Koala');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1517,NULL,'Adventures of the Monkey King');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6229,NULL,'Adventures of the Polar Cubs');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3604,NULL,'Adventures of the Young Shadar');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1811,NULL,'Adventures on Rainbow Pond');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1275,NULL,'Adventures With Iczer 3');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2277,NULL,'Aesop`s Fables');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9015,NULL,'Aesthetica of a Rogue Hero');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3966,NULL,'A Flying City Plan');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2001,NULL,'A Forbidden Time');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2656,NULL,'Afro Samurai');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6063,NULL,'Afro Samurai Resurrection');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11542,NULL,'Afro Samurai the Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2877,NULL,'After Class Lesson');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9331,NULL,'Afternoon Blush: More than Just Pure Love Mellow');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1637,NULL,'After School in the Teachers` Lounge');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1302,NULL,'After School Mania Club');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9164,NULL,'After School Midnighters');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8730,NULL,'After School NyanNyan');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8076,NULL,'Afterschool Pleiades');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2565,NULL,'Afterschool Romance Club');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2877,NULL,'After School: Wet Uniform');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3624,NULL,'After the man in the iron mask! from the Tale of d`Artagnan');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (755,NULL,'After War Gundam X');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3489,NULL,'A Full Throttle');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2161,NULL,'Agatha Christie`s Great Detectives Poirot and Marple');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11899,NULL,'Age 12');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10584,NULL,'Age 12.');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (280,NULL,'Agent Aika');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3606,NULL,'Age Of The Great Dinosaurs');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7044,NULL,'A Girl at Dojo Temple');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1090,NULL,'A Girl in a Lower Grade');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9765,NULL,'A Good Librarian Like a Good Shepherd');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10121,NULL,'A Grandma`s Goldfish');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3075,NULL,'A Great Super Shot Boy');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7738,NULL,'Agricultural Girls!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7944,NULL,'Agriculture');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7944,NULL,'Agriculture Angel Baraki');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7738,NULL,'Agriculture Girls!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (671,NULL,'A Heat for All Seasons');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3168,NULL,'Ah My Buddha');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3168,NULL,'Ah! My Buddha');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4145,NULL,'Ah My Buddha (2)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4145,NULL,'Ah My Buddha Season 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (27,NULL,'Ah! My Goddess');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7973,NULL,'Ah! My Goddess! (2011)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (186,NULL,'Ah! My Goddess: Being Small is Convenient');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4153,NULL,'Ah! My Goddess: Everyone Has Wings');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4153,NULL,'Ah! My Goddess Everyone`s Wings');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5426,NULL,'Ah! My Goddess: Fighting Wings');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4153,NULL,'Ah! My Goddess: Flights of Fancy');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (206,NULL,'Ah My Goddess! The Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (206,NULL,'Ah! My Goddess: The Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2533,NULL,'Ah! My Goddess TV');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5308,NULL,'A Hundred Percents');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4852,NULL,'Aika R-16 Virgin Mission');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11262,NULL,'Aikatsu! 3');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10580,NULL,'Ai-Mai-Mi - Mousou Catastrophie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (12506,NULL,'Ai-Mai-Mi Surgical Friends');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1072,NULL,'Aim for the Ace!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1074,NULL,'Aim for the Ace! (1979)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1390,NULL,'Aim for the Ace! 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1074,NULL,'Aim for the Ace! Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1073,NULL,'Aim for the Ace! TV 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1074,NULL,'Aim for the Best!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (185,NULL,'Aim for the top!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2002,NULL,'Air');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (198,NULL,'airbats');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7669,NULL,'Air Gear: Black Wings and Sleeping Forest - Break on the Sky');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1667,NULL,'air movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1667,NULL,'Air (Movie)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1667,NULL,'Air: The Motion Picture');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1667,NULL,'Air: The Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (74,NULL,'Ai Yori Aoshi');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1059,NULL,'Ai Yori Aoshi ~Enishi~');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10188,NULL,'A Jewish Girl in Shanghai');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (118,NULL,'Ajimu Beach Story');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11577,NULL,'Ajin: Demi-Human');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5479,NULL,'A Journey Through Fairyland');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10407,NULL,'Akame ga Kill!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6025,NULL,'Akane Iro ni Somaru Saka');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5492,NULL,'A Karate-Crazy Life');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11995,NULL,'Akashic records of bastard magic instructor');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8816,NULL,'AKB0048');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9330,NULL,'AKB0048: Next Stage');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1971,NULL,'Akiba Girls');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (12411,NULL,'Akiba`s Trip the Animation');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (509,NULL,'Akihabara Cyber Team');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2731,NULL,'Akihabara Cyber Team 2011');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7132,NULL,'Akikan! (2009)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1230,NULL,'Akiko');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7484,NULL,'Aki Sora: In a Dream');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7541,NULL,'A Kiss for the Petals');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7305,NULL,'A Komaneko Christmas: The Lost Present');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7685,NULL,'A-ko the Versus');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (223,NULL,'AL');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2270,NULL,'Aladdin and the Magic Lamp');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2270,NULL,'Aladdin and the Wonderful Lamp');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2199,NULL,'Alakazam the Great');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4144,NULL,'Alchemist Grade 3: Magical Pokahn');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11679,NULL,'Alderamin on the Sky');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10445,NULL,'Aldnoah.Zero');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10846,NULL,'Aldnoah.Zero (2015)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8270,NULL,'A Letter to Momo');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1194,NULL,'Alexander Record of War');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1194,NULL,'Alexander`s Campaign');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1194,NULL,'Alexander`s War Chronicles');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2871,NULL,'Alfred J. Kwak');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2871,NULL,'Alfred Jodocus Kwak');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2215,NULL,'Alibaba and the Forty Theives');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2215,NULL,'Alibaba`s Revenge');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1719,NULL,'Alice');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2435,NULL,'Alice Academy');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10628,NULL,'Alice in Borderland');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2744,NULL,'Alice in Wonderland');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2744,NULL,'Alice`s Adventures In Wonderland');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3084,NULL,'Alice`s Detective Agency');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1655,NULL,'Alien Defender Geo-Armor: Kishin Corps');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (861,NULL,'Alien from the Darkness');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (58,NULL,'Alien Nine');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3634,NULL,'Alien X from A Zone');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (147,NULL,'Alita');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6959,NULL,'A Literary Girl');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2298,NULL,'A Little Princess Sara');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9,NULL,'A Little Snow Fairy Sugar');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5569,NULL,'Allison and Lillia');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5569,NULL,'Allison & Lillia');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11580,NULL,'All Out!!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (167,NULL,'All Purpose Cultural Cat Girl Nuku Nuku');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (610,NULL,'All Purpose Cultural Cat Girl Nuku Nuku DASH!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (526,NULL,'All Purpose Cultural Cat Girl Nuku Nuku TV');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7920,NULL,'Alone Again');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6357,NULL,'A Lot of Pine Wood');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3667,NULL,'Alpenrose of Fire Judy and Randy');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2300,NULL,'Alps Stories: My Annette');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9,NULL,'ALSFS');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3389,NULL,'Always My Santa!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4039,NULL,'Always the Sun in My Soul');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7506,NULL,'Amagami SS');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8573,NULL,'Amagami SS +Plus');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10399,NULL,'Amagi Brilliant Park');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2318,NULL,'Amazing-man: The First Holy Demon War');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (115,NULL,'Amazing Nurse Nanako');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4887,NULL,'Amazing Nuts! 1');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4888,NULL,'Amazing Nuts! 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4889,NULL,'Amazing Nuts! 3');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4890,NULL,'Amazing Nuts! 4');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3466,NULL,'Amazing Sarutobi');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1463,NULL,'Ambassador Magma');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8869,NULL,'Ambition of Oda...');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (27,NULL,'AMG');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4153,NULL,'amg2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (206,NULL,'AMG Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4153,NULL,'amg s2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (206,NULL,'AMG - The Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2533,NULL,'amgtv');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2533,NULL,'amgtv1');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4153,NULL,'amgtv2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4153,NULL,'AMG TV 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7817,NULL,'Ami`s Journey');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5458,NULL,'Amuri');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5458,NULL,'Amuri in Star Ocean');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3533,NULL,'An Adventure in the Otaku Galaxy');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3452,NULL,'Anal Sanctuary');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8263,NULL,'Anal Vampire');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (470,NULL,'Ancient Books of Ys');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (471,NULL,'Ancient Books of Ys II');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7074,NULL,'Ancient Japanese Folktale: Ancient Boy');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4763,NULL,'Ancient Ruler Dinosaur King');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2220,NULL,'Andersen`s Children`s Story: The Mermaid Princess');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2208,NULL,'Andersen Stories');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2208,NULL,'Andersen story');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2314,NULL,'Anderson Stories');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (911,NULL,'Android Announcer Maico 2010');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (980,NULL,'Android Kikaider - The Animation');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7569,NULL,'And Yet the Town Moves');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11480,NULL,'And You Thought There Are No Girls On the Internet?');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11480,NULL,'And You Thought There Is Never a Girl Online?');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8148,NULL,'AnE');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1919,NULL,'Angel');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (687,NULL,'Angel Blade');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2803,NULL,'Angel Blade Punish!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (687,NULL,'Angel Blade Returns');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1919,NULL,'Angel Cloud');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2053,NULL,'Angel Core');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4347,NULL,'Angel Fighter');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5899,NULL,'Angel girl Jun');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (170,NULL,'Angelic Layer');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9346,NULL,'Angelic White Magical Girls');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3174,NULL,'Angelique: From the Sanctuary with Love');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2711,NULL,'Angelique: White Wing Memoirs');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2476,NULL,'Angelium');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3611,NULL,'Angel Legend');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (223,NULL,'Angel Links');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (910,NULL,'Angel of Darkness');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (29,NULL,'Angel Sanctuary');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9537,NULL,'Angel`s Drop');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (318,NULL,'Angel`s Egg');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (300,NULL,'Angels in the Court');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1405,NULL,'Angels in the Court 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1405,NULL,'Angels Return to the Court');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (175,NULL,'Angel`s Tail');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (680,NULL,'Angel`s Tail 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (175,NULL,'Angel Tails');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (175,NULL,'Angel Tales');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (680,NULL,'Angel Tales 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (680,NULL,'Angel Tales OVA');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10962,NULL,'Ange Vierge');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2578,NULL,'Angie Girl');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3562,NULL,'Animal Alley');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4590,NULL,'Animal Crossing');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6788,NULL,'Animal Detectives Kiruminzoo');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3562,NULL,'Animal Lane');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6841,NULL,'Animal Olympic Games');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6742,NULL,'Animal Sumo');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3518,NULL,'Animal Village Stories');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2277,NULL,'Animated Aesop`s Fables');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3662,NULL,'Animated Call of the Wild');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3676,NULL,'Animated Children`s Stories of the World');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2427,NULL,'Animated Classics of Japanese Literature');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5519,NULL,'Animated Japanese Picture Scrolls');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3083,NULL,'Animated Tamagotchi Found on Television!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1962,NULL,'Animated Three Musketeers');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3592,NULL,'Animation of World Folklore');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (773,NULL,'Animation Runner Kuromi');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1803,NULL,'Animation Runner Kuromi 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5315,NULL,'Animation Store Manager');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11540,NULL,'eanime de Training! Ex');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (12301,NULL,'eanime de Training! XX');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3662,NULL,'eanime Shout of the Wilderness');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11540,NULL,'Anitore! EX');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2200,NULL,'Anju and Zushiomaru');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1061,NULL,'Anne of Green Gables');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7526,NULL,'Anne of Green Gables: Road to Green Gables');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8181,NULL,'Ano Hana');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9356,NULL,'Anohana Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8181,NULL,'Anohana: The Flower We Saw That Day');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9356,NULL,'AnoHana: The Flower We Saw That Day: The Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2385,NULL,'An Olympic Fable: Run for Life');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1113,NULL,'Another Lady Innocent');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8625,NULL,'Another The Other -Karma-');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9916,NULL,'AnR');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11705,NULL,'Anthology With Cranes');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6989,NULL,'Anthropo-Cynical Farce');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5031,NULL,'Anti-Demon Hunters');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5031,NULL,'Anti-Demon Ninja Asagi');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10598,NULL,'Antimagic Academy 35th Test Platoon');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10598,NULL,'Anti-Magic Academy: The 35th Test Platoon');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5971,NULL,'Antique Bakery');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2012,NULL,'Anyone You Can Do... I Can Do Better!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (910,NULL,'aod');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11110,NULL,'Aoharu x Machinegun');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1470,NULL,'Aoi & Mutsuki: A Pair of Queens');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9091,NULL,'Aoi Sekai no Chushin de');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10934,NULL,'Aokana: Four Rhythm Across the Blue');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9541,NULL,'AoT');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9541,NULL,'AoT TV');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1902,NULL,'Apache Baseball Team');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11838,NULL,'Ape Escape Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7597,NULL,'A Penguin`s Troubles Max');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6473,NULL,'Apocalypse Meow');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (44,NULL,'Apocalypse of Devilman');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (928,NULL,'Apocalypse Zero');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3416,NULL,'Appleland Story');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (166,NULL,'Appleseed');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5080,NULL,'appleseed2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1312,NULL,'Appleseed (2004)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10636,NULL,'Appleseed Alpha');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5080,NULL,'Appleseed: Ex Machina');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8055,NULL,'Appleseed XIII');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8311,NULL,'Appleseed XIII: Tartaros & Ouranos');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (572,NULL,'Aqua Age');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8,NULL,'Aquarian Age: Sign for Evolution');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2456,NULL,'Aquarian Age: The Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2830,NULL,'Aquarion');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8299,NULL,'Aquarion Evol');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11150,NULL,'Aquarion Logos');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4600,NULL,'Aquarion OVA');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5390,NULL,'Aquarion the Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5154,NULL,'Aquatic');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4346,NULL,'Aquatic Language');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (785,NULL,'Arabian Nights: Sinbad`s Adventures');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1779,NULL,'Arabian Nights: Sinbad the Sailor');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1192,NULL,'Araiso Private High School Student Council Executive Committee');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7238,NULL,'Arakawa Under the Bridge');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7899,NULL,'Arakawa Under the Bridge x Bridge');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9551,NULL,'Arata: The Legend');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (728,NULL,'Arcadia of My Youth');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (726,NULL,'Arcadia of My Youth: Infinite Course SSX');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9287,NULL,'Archenemy and Hero');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7000,NULL,'Archer without a Bow');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (569,NULL,'Area 88 OVA');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1306,NULL,'Area 88 TV');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2414,NULL,'Arei`s Mirror');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (50,NULL,'Argentosoma');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10550,NULL,'Argevollen');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2659,NULL,'Aria the Animation');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4243,NULL,'Aria the Natural');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5424,NULL,'Aria the Origination');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5115,NULL,'Aria the OVA: Arietta');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8109,NULL,'Aria the Scarlet Ammo');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10980,NULL,'Aria the Scarlet Ammo AA');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4867,NULL,'Ari Doll');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3404,NULL,'Arisa');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (107,NULL,'Arjuna');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (773,NULL,'ark');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9534,NULL,'arknine');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9534,NULL,'Ark Nine');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4322,NULL,'Ark of Awakening');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4265,NULL,'Armada of Glass');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6679,NULL,'Armed Librarians');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6679,NULL,'Armed Librarians: Book of Bantorra');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (420,NULL,'Armitage');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (420,NULL,'Armitage III');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (237,NULL,'Armitage III: Dual Matrix');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (236,NULL,'Armitage III: Poly Matrix');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9237,NULL,'Armored Angels');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8513,NULL,'Armored Angels - Moon Angel');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2008,NULL,'Armored Dragon Legend Villgust');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2041,NULL,'Armored Fleet Dairugger XV');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1370,NULL,'Armored Genesis Mospeada');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5541,NULL,'Armored Knight Iris');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3049,NULL,'Armored Police Metal Jack');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2589,NULL,'Armored Rescue Team Restol');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2041,NULL,'Armored Squadron Dairugger XV');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4359,NULL,'Armored Trooper Dorvack');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7433,NULL,'Armored Troopers J-Phoenix PF Lips Team');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1698,NULL,'Armored Trooper Votoms');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7920,NULL,'Armored Trooper Votoms: Alone Again');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5126,NULL,'Armored Trooper Votoms: Big Battle');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7918,NULL,'Armored Trooper Votoms Case;Irvine');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5131,NULL,'Armored Trooper Votoms: Pailsen Files');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6722,NULL,'Armored Trooper Votoms: Pailsen Files - The Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7279,NULL,'Armored Trooper Votoms: Phantom Arc');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4842,NULL,'Armored Trooper Votoms: Roots of Ambition');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3998,NULL,'Armored Trooper Votoms: Shining Heresy');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3998,NULL,'Armored Trooper Votoms: The Brilliant Heretic');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3998,NULL,'Armored Trooper Votoms: The Defrost');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5125,NULL,'Armored Trooper Votoms: The Last Red Shoulder');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1161,NULL,'Armor Hunter Mellowlink');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (460,NULL,'Armor Legend Samurai Troopers');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1161,NULL,'Armor Soldier Merrowlink');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4516,NULL,'Arms Alchemy');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2706,NULL,'Around the World in Eighty Days');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2706,NULL,'Around the World with Willy Fog');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9905,NULL,'Arpeggio of Blue Steel');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1681,NULL,'Arrow Emblem: Hawk of the Grand Prix');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6231,NULL,'Artificial Girl: Transforming Sex Android');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (980,NULL,'Artificial Humanoid Kikaider');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4756,NULL,'Artificial Insect Kabutoborg');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1068,NULL,'Art of Fighting');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4156,NULL,'ar tonelico');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4156,NULL,'Ar tonelico: The Girl Who Sings at the End of the World');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3308,NULL,'Arusu2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (29,NULL,'AS');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3440,NULL,'a`s');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10533,NULL,'A School Where Love Is Unnecessary');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6200,NULL,'A Sea Turtle and a Boy');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1102,NULL,'Asgaldh: The Distortion Testament');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7888,NULL,'Asience: Hairy Tale');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10937,NULL,'A Silent Voice');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (541,NULL,'Ask Dr. Rin');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10702,NULL,'Assassination Classroom');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11203,NULL,'Assassination Classroom 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9985,NULL,'Assassination Classroom (2013)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10702,NULL,'Assassination Classroom (2015)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11203,NULL,'Assassination Classroom: Final Season');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11203,NULL,'Assassination Classroom: Second Season');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10702,NULL,'ass class');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1158,NULL,'Assemble Insert');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1521,NULL,'Association Robot Goku');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8062,NULL,'Astarotte`s Toy');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8062,NULL,'Astarotte Toy');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10082,NULL,'A Starry Tale');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1821,NULL,'Asteroid Mask');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2238,NULL,'Astonishment man Batsealer');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11711,NULL,'A Story in Summertime');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5192,NULL,'A Strange Kind of Woman');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (807,NULL,'Astroboy');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1440,NULL,'Astro Boy');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1446,NULL,'Astro Boy (1980)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (807,NULL,'Astro Boy (2003)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1513,NULL,'Astro Boy: Shinsengumi');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1514,NULL,'Astro Boy: THE BRAVE IN SPACE');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6049,NULL,'Astro Fighter Sunred');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6777,NULL,'Astro Fighter Sunred 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3079,NULL,'Astro Ganga');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10186,NULL,'Astro Plan');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6262,NULL,'A Summer Day`s Dream');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7877,NULL,'A Summer Night`s Dream');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6769,NULL,'Asura2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6374,NULL,'Asura Cryin` 1');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6493,NULL,'Asylum Session');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (175,NULL,'at');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (680,NULL,'at2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4607,NULL,'Atagoal is Cat`s Forest');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (702,NULL,'A Tail of Two Sisters');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5612,NULL,'A Tale of Seven Cities - the Arctic Front');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3608,NULL,'Atashinchi Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10241,NULL,'Atelier Escha & Logy - Alchemists of the Dusk Sky');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10241,NULL,'Atelier Escha & Logy: Alchemists of the Dusk Sky');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8106,NULL,'A Thirty-Year Old`s Health and Physical Education');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3683,NULL,'A Thousand and One Nights');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5499,NULL,'A Thousand and One Nights (1998)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3683,NULL,'A Thousand & One Nights');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5382,NULL,'A Time Slip of 10000 Years: Prime Rose');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2264,NULL,'A Time To Screw');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5497,NULL,'At Last! Turtle Detective Agency');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9751,NULL,'A Town Where You Live');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8587,NULL,'A Town Where You Live: Twilight Crossing');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3464,NULL,'A Traveller`s Diary');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6996,NULL,'A Travel to the Lost World');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1508,NULL,'A Tree in a Sunny Place');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (604,NULL,'A Tree of Palme');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (757,NULL,'Attack #1');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (757,NULL,'Attack # 1');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (757,NULL,'Attack No.1');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (757,NULL,'Attack No. 1');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (757,NULL,'Attack Number 1');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (757,NULL,'Attack Number One');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9541,NULL,'Attack on Titan');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11468,NULL,'Attack on Titan: Junior High');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9826,NULL,'Attack on Titan OAD');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10944,NULL,'Attack on Titan Season 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10583,NULL,'Attack on Titan - The Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3076,NULL,'Attack on Tomorrow');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6398,NULL,'At The Mercy of The Sky');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8094,NULL,'Attraction');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5889,NULL,'Auction: Beautiful Slave');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11662,NULL,'Audition');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10315,NULL,'A.U.F.L. : au Unlimited Future Laboratory');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9007,NULL,'Au Fou!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2738,NULL,'Aunt Spoon');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4356,NULL,'Aura');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (899,NULL,'Aura Battler Dunbine');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2468,NULL,'Aura Battler Dunbine - The Tale of Neo Byston Well');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9294,NULL,'Aura: Koga Maryuin`s Last War');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (109,NULL,'Automatic Maiden');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10409,NULL,'Avengers Confidential: Black Widow & Punisher');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4060,NULL,'A Well-Ordered Restaurant (1991)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11948,NULL,'A Well-Ordered Restaurant (1994)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (200,NULL,'A Wind Named Amnesia');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8208,NULL,'A Wind Skimming the River`s Surface');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6234,NULL,'Axis Powers Hetalia');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3654,NULL,'Ayakashi - Samurai Horror Tales');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (997,NULL,'Ayane`s High Kick');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4785,NULL,'Ayu Mayu Theater');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (106,NULL,'Azumanga Daioh');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8793,NULL,'Azumanga Daioh - The Very Short Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8793,NULL,'Azumanga Daioh: The Very Short Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1760,NULL,'\"Azusa');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1760,NULL,'Azusa Will Help!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (504,NULL,'ba');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1460,NULL,'Babel II');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1461,NULL,'Babel II (1992)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (655,NULL,'Babel II: Beyond Infinity');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1648,NULL,'\"Babe');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1419,NULL,'Baby and Me');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4616,NULL,'Baby Dinosaur Dooly');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9710,NULL,'Baby Dinosaur Dooly (1988)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9712,NULL,'Baby Dinosaur Dooly (1996)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9713,NULL,'Baby Dinosaur Dooly (2008)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3635,NULL,'Baby Grandma');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6729,NULL,'Baby Kangaroo`s Birthday Surprise');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9710,NULL,'Baby Saurus Dooly (1988)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2295,NULL,'Back to the Forest');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7827,NULL,'Bad Badtz-Maru in The Boy Who Cried Wolf');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7842,NULL,'Bad Badtz-maru`s The Ants and the Grasshopper');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2375,NULL,'Bad Teacher Equation');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1856,NULL,'Baggy');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1856,NULL,'\"Bagi');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6747,NULL,'Baka and Test: Summon the Beasts');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8235,NULL,'Baka and Test: Summon the Beasts (2)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8085,NULL,'Baka and Test: Summon the Beasts - OVA');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6327,NULL,'bakemono');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6327,NULL,'Bakemonogatari');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (453,NULL,'Baki The Grappler');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7401,NULL,'Bakugan Battle Brawlers: New Vestroia');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8391,NULL,'Bakugan: Mechtanium Surge');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8150,NULL,'Bakuman S2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8836,NULL,'Bakuman S3');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (618,NULL,'BAKUNYU Hyper-Battle Ikki Tousen');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2903,NULL,'Baku Yumemakura`s Twilight Theatre');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11796,NULL,'Balala the Fairies');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11833,NULL,'Balala the Fairies 3 Finding Melody');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (12565,NULL,'Balala the Fairies: Miracle Dance');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3445,NULL,'Baldr Force EXE');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3572,NULL,'Ballad of a Shinigami');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11419,NULL,'Balloon');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1395,NULL,'Balthus: Tia`s Radiance');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5356,NULL,'Bamboo Blade');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (555,NULL,'Bandit King Jing');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (12570,NULL,'Bangable Girl');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4,NULL,'Banner of the Stars');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5,NULL,'Banner of the Stars 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2673,NULL,'Banner of the Stars 3');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5,NULL,'Banner of the Stars II');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2673,NULL,'Banner of the Stars III');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (884,NULL,'Banner of the Stars Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2383,NULL,'Bannertail: The Story of Gray Squirrel');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (941,NULL,'Baoh');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (941,NULL,'Baoh the Visitor');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (848,NULL,'ba ova');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4044,NULL,'Barbapapa Around the World');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2011,NULL,'Barefoot Gen 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4779,NULL,'Baribari Legend');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3956,NULL,'Bark! Bunbun');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3304,NULL,'Bark! Bun Bun');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3956,NULL,'Bark! Bun Bun Special');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4574,NULL,'Barrier Master');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2436,NULL,'Basilisk');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2436,NULL,'Basilisk: Super-Refined Ninja Arts');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2436,NULL,'Basilisk: The Kouga Ninja Scrolls');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10,NULL,'Bastard!!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10,NULL,'Bastard! Destroyer of Darkness');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1219,NULL,'Bastof Lemon');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1219,NULL,'BAST oF Syndrome');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (147,NULL,'Battle Angel');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (147,NULL,'Battle Angel Alita');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9327,NULL,'Battle Angel Alita - Motorball CG Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1293,NULL,'Battle Arena Toshinden');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (848,NULL,'Battle Athletes');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (848,NULL,'Battle Athletes OVA');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (504,NULL,'Battle Athletes Victory');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2082,NULL,'Battle Ball');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1372,NULL,'Battle B-Daman');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2545,NULL,'Battle Can-Can');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (170,NULL,'Battle Doll Angelic Layer');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (111,NULL,'Battle Fairy Yukikaze');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4,NULL,'Battle Flag of the Stars');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5,NULL,'Battle Flag of the Stars 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (884,NULL,'Battle Flag of The Stars Special');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6172,NULL,'Battle for Beauty');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8254,NULL,'Battle Girls: Time Paradox');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4251,NULL,'Battle-Maiden Valkyrie True Chapter');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3513,NULL,'Battle of the Planets');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1462,NULL,'Battle Royal High School');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (554,NULL,'Battle Skipper School');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1068,NULL,'Battle Spirits: Dragon Tiger Fist');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1399,NULL,'Battle Team Lakers EX');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (618,NULL,'Battle Vixens');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (504,NULL,'bav');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (504,NULL,'BA:V');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5150,NULL,'Bavel`s Book');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1095,NULL,'BBDR');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11761,NULL,'BBK/BRNK');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7286,NULL,'B-cup H-group');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8555,NULL,'B-Daman Crossfire');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1082,NULL,'Beast City');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (709,NULL,'Beast Fighter');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4157,NULL,'Beast-God Riger');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3507,NULL,'Beast King Golion');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3456,NULL,'Beast Warriors Gulkeeva');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7061,NULL,'Beast Wars Metals: Convoy Great Transformation');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4202,NULL,'Beast Wars Neo');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2978,NULL,'Beast Wars Second Lio Convoy Special');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (309,NULL,'Beat Angel Escalayer');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6561,NULL,'Beat Blades Haruka');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2820,NULL,'Beating Angel Dokuro-chan');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11104,NULL,'Beautiful Bones: Sakurako`s Investigation');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2722,NULL,'Beautiful Girl Comic Lolita Complex Angel: Taste of Honey');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2611,NULL,'Beautiful Joe');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10972,NULL,'Beautiful Little Sister! Umaru-chan');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11968,NULL,'Beautiful World');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7978,NULL,'Because I Don`t Like My Big Brother at All!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7541,NULL,'Becoming your lover');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2825,NULL,'Bedaman: Fire Spirits');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6772,NULL,'bee');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7458,NULL,'bee2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7736,NULL,'Beelzebub: The Baby I Picked Up Is the Great Demon King!?');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3703,NULL,'Beet Excellion');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2391,NULL,'Beet the Vandel Buster');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3703,NULL,'Beet the Vandel Buster 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3703,NULL,'Beet the Vandel Buster Excellion');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2239,NULL,'Be Forever Yamato');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11536,NULL,'Beginning of Fashion');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (776,NULL,'Behind Closed Doors');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10579,NULL,'\"Being a Photo Shoot Model Under the Blazing Sun Isn`t Easy');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2739,NULL,'Belfi & Lilibit');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2739,NULL,'Belfy and Lillabit');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4205,NULL,'Be Lifesized My Lover - Mechanic Minami vs. Human Minami');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3289,NULL,'Belladonna of Sadness');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3289,NULL,'Belladonna of Sorrow');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3305,NULL,'Belle and Sebastian');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3551,NULL,'Bell of Chirin');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6744,NULL,'Belly Drum Dance at Shojoji Temple');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6744,NULL,'Belly Drumming at Shoujouji Temple');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7988,NULL,'Beloved Wife Diaries');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6859,NULL,'Benkei vs Ushiwaka');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (98,NULL,'Berserk');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7991,NULL,'Berserk Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7991,NULL,'Berserk: The Golden Age Arc');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4455,NULL,'Bestial Warrior Psychic Wars');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1398,NULL,'Best of Kitty #1 (1)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1397,NULL,'Best of Kitty #1 (2)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1399,NULL,'Best of Kitty #1 (3)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1394,NULL,'Best of Kitty #2 (1)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1396,NULL,'Best of Kitty #2 (2)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1395,NULL,'Best of Kitty #2 (3)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1400,NULL,'Best of Kitty #3 (1)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1401,NULL,'Best of Kitty #3 (2)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1402,NULL,'Best of Kitty #3 (3)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1363,NULL,'Best of Kitty #4 (1)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (664,NULL,'Best of Kitty #4 (2)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1403,NULL,'Best of Kitty #4 (3)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2964,NULL,'Best Student Council');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6818,NULL,'Betrayal Knows My Name');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1731,NULL,'Between the Realms of Desire & Envy');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2650,NULL,'Bewitched Agnes');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2650,NULL,'Bewitched Bride');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (595,NULL,'Beyblade');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (594,NULL,'Beyblade G Revolution');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8298,NULL,'Beyblade: Metal Fury');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6426,NULL,'Beyblade: Metal Fusion');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7426,NULL,'Beyblade: Metal Masters');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9048,NULL,'Beyblade: Shogun Steel');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4016,NULL,'Beyblade the Movie: Decisive Battle! Takao VS Daichi');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4016,NULL,'Beyblade the Movie: Fierce Battle');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1964,NULL,'Beyblade V Force');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3118,NULL,'Beyond');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9518,NULL,'Beyond the Boundary');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (469,NULL,'Beyond The Clouds');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (469,NULL,'\"Beyond The Clouds');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6408,NULL,'Beyond the Heavens');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4058,NULL,'Beyond the Stream of Time: A Dance in the Moonlight');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4188,NULL,'Beyond the Train Tracks');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1092,NULL,'BF');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4,NULL,'BFotS');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5,NULL,'BFotS2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7286,NULL,'B Gata H Kei: Yamada`s First Time');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (528,NULL,'Bible Black');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1693,NULL,'Bible Black: New Testament');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3430,NULL,'Bible Black Only');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (829,NULL,'Bible Black Origins');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1693,NULL,'Bible Black Revival');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9010,NULL,'Big Breasts Fantasy');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8156,NULL,'Big Fish & Begonia');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8156,NULL,'Big Fish & Chinese Flowering Crabapple');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11724,NULL,'Big Order');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (904,NULL,'Big O Roger');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1464,NULL,'Big Wars');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4923,NULL,'Big Windup!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7291,NULL,'Big Windup! 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7291,NULL,'Big Windup! Season 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7291,NULL,'Big Windup! The Summer Tournament');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11251,NULL,'Bikini Warriors');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (619,NULL,'Bio-Booster Armor Guyver');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4855,NULL,'Bird`s Song');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6120,NULL,'birdy2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1945,NULL,'Birdy the Mighty');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5722,NULL,'Birdy the Mighty: Decode');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7013,NULL,'Birdy the Mighty Decode 0');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6120,NULL,'Birdy the Mighty: Decode 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6120,NULL,'Birdy the Mighty: Decode (2)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7013,NULL,'Birdy the Mighty Decode - The Cipher');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7013,NULL,'Birdy the Mighty Decode: The Cipher');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1155,NULL,'Birth Debut');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3509,NULL,'Birth of Japan');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11317,NULL,'Birth of Kitarou');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (804,NULL,'Bizarre Cage');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3506,NULL,'BJ Movie (2005)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4416,NULL,'Black Blood Brothers');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1181,NULL,'Blackboard Jungle');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10181,NULL,'Black Bullet');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6048,NULL,'Black Butler');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10402,NULL,'Black Butler: Book of Circus');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10548,NULL,'Black Butler: Book of Murder');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7369,NULL,'Black Butler II');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3321,NULL,'Black Cat');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9630,NULL,'Black Dragon King and Asylum Baluster');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2254,NULL,'Black Gate');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6211,NULL,'Black God');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (406,NULL,'Black Heaven');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2544,NULL,'Black Jack (1993)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3119,NULL,'Black Jack: Capital Transfer To Heian');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3506,NULL,'Black Jack Movie (2005)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2672,NULL,'Black Jack Special: The 4 Miracles of Life');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3119,NULL,'Black Jack: Tezuka World Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2672,NULL,'Black Jack: The 4 Miracles of Life');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7387,NULL,'Black Jack: The Boy Who Came from the Sky');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (686,NULL,'Black Jack: The Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3506,NULL,'Black Jack: The Two Black Doctors');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3506,NULL,'Black Jack: The Two Doctors of Darkness');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2389,NULL,'Black Jack TV');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3395,NULL,'Black Lagoon');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6645,NULL,'Black Lagoon: Roberta`s Blood Trail');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4597,NULL,'Black Lagoon: The Second Barrage');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2613,NULL,'Black Lion');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (578,NULL,'Black Magic M-66');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (243,NULL,'Blackmail');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (774,NULL,'Blackmail 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10201,NULL,'Black Nest Chronus');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8584,NULL,'Black Rock Shooter');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6546,NULL,'Blacksmith');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4054,NULL,'Black & White');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1598,NULL,'Black Widow');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9999,NULL,'Blade Dance of Elementalers');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5679,NULL,'Blade of the Immortal');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2190,NULL,'Blade of the Phantom Mask');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2190,NULL,'Blade of the Phantom Master');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5531,NULL,'Blassreiter');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4702,NULL,'Blast Ball Rapid Fire! Super B-Daman');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9214,NULL,'Blast of Tempest');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9893,NULL,'BlazBlue: Alter Memory');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8559,NULL,'Blazing Alpenrose OVA');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7278,NULL,'Blazing Night Raid');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2980,NULL,'Blazing Transfer Student');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6041,NULL,'Bleach: Fade to Black');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6041,NULL,'BLEACH Fade to Black : I call your name');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7666,NULL,'Bleach: Hell Chapter');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4515,NULL,'Bleach Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4515,NULL,'Bleach Movie 1');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5352,NULL,'Bleach Movie 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6041,NULL,'Bleach Movie 3');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7666,NULL,'Bleach Movie 4');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5352,NULL,'BLEACH The DiamondDust Rebellion Another Hyourinmaru');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5352,NULL,'Bleach the Movie 2: The Diamond Dust Rebellion');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6041,NULL,'Bleach The Movie 3: Fade to Black');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6041,NULL,'Bleach the Movie 3: Fade to Black - I Call Your Name');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7666,NULL,'Bleach the Movie 4: Hell Verse');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4515,NULL,'Bleach the Movie: Memories of Nobody');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5352,NULL,'BLEACH The Movie: The DiamondDust Rebellion Another Hyourinmaru');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2825,NULL,'B-Legend! Battle Bedaman Fire Spirits');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7280,NULL,'Blessing of the Campanella');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8243,NULL,'Blessing of the Campanella (2011)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2021,NULL,'Blocker Corps');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3653,NULL,'Blonde Jeanie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3186,NULL,'Blood+');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10663,NULL,'Blood Blockade Battlefront');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (12571,NULL,'Blood Blockade Battlefront & Beyond');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8348,NULL,'BLOOD-C');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8375,NULL,'Blood-C: The Last Dark');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (12372,NULL,'Bloodivores');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8929,NULL,'Blood Lad');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9803,NULL,'Blood Lad: I Am Not a Cat');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9803,NULL,'Blood Lad: I`m not a cat');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7477,NULL,'Blood of the Reprimanded Hound');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (347,NULL,'Blood Reign');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (347,NULL,'Blood Reign: Curse of the Yoma');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1599,NULL,'Blood Royale');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1599,NULL,'Blood Royal Princess');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1345,NULL,'Bloodshadow');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1345,NULL,'Blood Shadow');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (43,NULL,'Blood: The Last Vampire');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2820,NULL,'Bludgeoning Angel Dokuro-chan');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5089,NULL,'Bludgeoning Angel Dokuro-chan 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2559,NULL,'Blue Blink');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2154,NULL,'Blue Comet SPT Layzner');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2155,NULL,'Blue Comet SPT Layzner OVA');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5044,NULL,'Blue Dragon');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5869,NULL,'Blue Dragon 2');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5869,NULL,'Blue Dragon: The Seven Dragons of the Sky');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5869,NULL,'Blue Dragon: Trials of the Seven Shadows');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5383,NULL,'Blue Drop');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8148,NULL,'Blue Exorcist');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (12240,NULL,'Blue Exorcist: Kyoto Saga');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8689,NULL,'Blue Exorcist: The Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (5897,NULL,'Blue Fairy');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (4314,NULL,'Blue Flames');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2357,NULL,'Blue Gale XABUNGLE');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (416,NULL,'Blue Gender');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (771,NULL,'Blue Gender Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (771,NULL,'Blue Gender The Movie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (771,NULL,'Blue Gender: The Warrior');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (572,NULL,'Blue Green Years');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10882,NULL,'Blue jacket');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1840,NULL,'Blue Legend Shoot!');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2097,NULL,'Blue Legend Shoot! (1994)');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7056,NULL,'BlueLit');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7056,NULL,'Blue Literature Series');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11408,NULL,'Blue Room');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (74,NULL,'Bluer than Indigo');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1059,NULL,'Bluer than Indigo ~Fate~');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (385,NULL,'Blue Seed Beyond');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (385,NULL,'Blue Seed OVA');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (198,NULL,'Blue Sky Girl Squadron');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2887,NULL,'Blue Sonnet');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (361,NULL,'Blue Submarine No.6');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10060,NULL,'Blue Uru');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3546,NULL,'Bobby`s Girl');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3546,NULL,'Bobby`s In Deep');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2740,NULL,'Bob in a Bottle');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1180,NULL,'Bobobo-bo Bo-bobo');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (9293,NULL,'Bodacious Space Pirates: Abyss of Hyperspace');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (103,NULL,'Bodyguard of the Wind');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1852,NULL,'Body Transfer');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2032,NULL,'Body Wash The Animation');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (387,NULL,'BOF');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1092,NULL,'bofa');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8658,NULL,'Bogustory');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11044,NULL,'Boku no Yayoi-san');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11559,NULL,'Bologee Story');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (8766,NULL,'Bomahead');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (2060,NULL,'Bomber Bikers of Shonan');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3217,NULL,'Bomb Milk Sisters');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1711,NULL,'Bondage 101');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1014,NULL,'Bondage Game');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1363,NULL,'Bondage House');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (1272,NULL,'Bondage Mansion');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (933,NULL,'Bondage Queen Kate');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (10780,NULL,'Bonjour Sweet Love Patisserie');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (11843,NULL,'Bono Bono');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (3043,NULL,'Boobalicious');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (6114,NULL,'Booby Life');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (179,NULL,'Boogiepop Phantom');
INSERT INTO `atitles` (`aid`,`japtitle`,`entitle`) VALUES (7441,NULL,'Book Girl Memories');
